### ISSUE TITLE
Switch UI - plain checkboxes are displayed instead of the styled content

### ISSUE THREAD

**Issue by workpaul** [tehapo/Switch#4]
I'm using the component ( v. 2.0.1) with the Vaadin 7.2.4 and the widgetset was recompiled without issues. However in the application the switch component is displayed as a regular checkbox.

**Comment by tehapo** [comment]
This happens when the client-side implementation of Switch component is missing from the widgetset. Please verify the following:

* The widgetset is compiled and the following line appears in the compilation output:
```Visiting SwitchConnector with ConnectorInitVisitor```

* The widgetset of your application (*.gwt.xml file) inherits the add-on with the following line: ```<inherits name="org.vaadin.teemu.switchui.SwitchComponentWidgetset" />``` ([example](https://github.com/tehapo/Switch/blob/master/switch-demo/src/main/resources/org/vaadin/teemu/switchui/demo/SwitchDemoWidgetset.gwt.xml))
